.TH "include Directory Reference" 3 "Sat Aug 7 2021" "Version 2.0" "nanows" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig\&.h\fP"
.br
.RI "Function Prototypes for the configuration manager\&. "
.ti -1c
.RI "file \fBhelpers\&.h\fP"
.br
.RI "Function Prototypes for commonly used helper functions\&. "
.ti -1c
.RI "file \fBmimetypes\&.h\fP"
.br
.RI "Function Prototypes for loading and querying MIME types\&. "
.ti -1c
.RI "file \fBrequest\&.h\fP"
.br
.RI "Function Prototypes for accepting, parsing and handling network requests\&. "
.ti -1c
.RI "file \fBresponse\&.h\fP"
.br
.RI "Function Prototypes for creating, sending and handling network responses\&. "
.in -1c
