.TH "slib Directory Reference" 3 "Sun Aug 8 2021" "Version 2.0" "nanows" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slib Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig\&.c\fP"
.br
.RI "A configuration manager\&. "
.ti -1c
.RI "file \fBhelpers\&.c\fP"
.br
.RI "Collection of commonly used helper functions\&. "
.ti -1c
.RI "file \fBmimetypes\&.c\fP"
.br
.RI "Functions for loading and querying mimetypes\&. "
.ti -1c
.RI "file \fBrequest\&.c\fP"
.br
.RI "Functions for accepting, parsing and handling network requests\&. "
.ti -1c
.RI "file \fBresponse\&.c\fP"
.br
.RI "Functions for creating, sending and handling network responses\&. "
.ti -1c
.RI "file \fBserver\&.c\fP"
.br
.RI "Functions for loading configuration, starting and stopping the server, memory management and for handling the server's main loop\&. "
.in -1c
