.TH "bug" 3 "Sat Aug 7 2021" "Version 2.0" "nanows" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBFile \fBconfig\&.c\fP \fP" 1c
No known bugs\&.  
.IP "\fBFile \fBconfig\&.h\fP \fP" 1c
No known bugs\&.  
.IP "\fBFile \fBhelpers\&.c\fP \fP" 1c
No known bugs\&.  
.IP "\fBFile \fBhelpers\&.h\fP \fP" 1c
No known bugs\&.  
.IP "\fBFile \fBmimetypes\&.c\fP \fP" 1c
No known bugs\&.  
.IP "\fBFile \fBmimetypes\&.h\fP \fP" 1c
No known bugs\&.  
.IP "\fBFile \fBrequest\&.c\fP \fP" 1c
No known bugs\&.  
.IP "\fBFile \fBrequest\&.h\fP \fP" 1c
No known bugs\&.  
.IP "\fBFile \fBresponse\&.c\fP \fP" 1c
No known bugs\&.  
.IP "\fBFile \fBresponse\&.h\fP \fP" 1c
Respose headers cannot be modified or removed as of now\&. This is a known issue and will be fixed in the future\&. 
.PP
\fC\fBsend_response_head()\fP\fP: Function doesn't return error code\&. 
.PP
\fC\fBsend_response_file()\fP\fP: No easy way to confirm that the file was sent sucessfully\&. Known issue and will be fixed in the future\&.  
.IP "\fBFile \fBserver\&.c\fP \fP" 1c
No known bugs\&. 
.PP

