.TH "include/config.h" 3 "Sun Aug 8 2021" "Version 2.0" "nanows" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/config.h \- Function Prototypes for the configuration manager\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <glib\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONF_FILE\fP   '\&./etc/nanows\&.conf'"
.br
.RI "Defines the default configuration file in INI file format\&. "
.ti -1c
.RI "#define \fBGROUP_NAME\fP   'server'"
.br
.RI "Defines the default group name for server configuration options\&. "
.ti -1c
.RI "#define \fBHOST_CONF_KEY\fP   'server_host'"
.br
.RI "Defines the default configuration key for Server IP\&. "
.ti -1c
.RI "#define \fBPORT_CONF_KEY\fP   'server_port'"
.br
.RI "Defines the default configuration key for Server Port\&. "
.ti -1c
.RI "#define \fBSITE_DIR_CONF_KEY\fP   'site_root_dir'"
.br
.RI "Defines the default configuration key for website root directory\&. "
.ti -1c
.RI "#define \fBPAGE_CONF_KEY\fP   'default_page'"
.br
.RI "Defines the default configuration key for website default file\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBload_config\fP ()"
.br
.RI "Loads and parses the configuration file and returns an int value to indicate success or failure\&. "
.ti -1c
.RI "char * \fBget_config\fP (const char *)"
.br
.RI "Returns the value for the corresponding configuration key\&. "
.ti -1c
.RI "char * \fBget_config_str\fP (const char *)"
.br
.RI "Returns the value for the corresponding configuration key\&. "
.ti -1c
.RI "int \fBget_config_int\fP (const char *)"
.br
.RI "Returns the int value for the corresponding configuration key\&. "
.ti -1c
.RI "void \fBunload_config\fP ()"
.br
.RI "Unloads configuration and frees memory allocated for configuration and any errors\&. "
.in -1c
.SH "Detailed Description"
.PP 
Function Prototypes for the configuration manager\&. 

This file contains function prototypes for loading, retriving configurations from file defined by \fCCONF_FILE\fP macro\&.
.PP
Implemented in \fC\fBslib/config\&.c\fP\fP\&.
.PP
\fBAuthor\fP
.RS 4
Sai Hemanth Bheemreddy (@SaiHemanthBR) 
.RE
.PP
\fBCopyright\fP
.RS 4
MIT License; Copyright (c) 2021 Sai Hemanth Bheemreddy 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define CONF_FILE   '\&./etc/nanows\&.conf'"

.PP
Defines the default configuration file in INI file format\&. 
.SS "#define GROUP_NAME   'server'"

.PP
Defines the default group name for server configuration options\&. 
.SS "#define HOST_CONF_KEY   'server_host'"

.PP
Defines the default configuration key for Server IP\&. 
.SS "#define PAGE_CONF_KEY   'default_page'"

.PP
Defines the default configuration key for website default file\&. 
.SS "#define PORT_CONF_KEY   'server_port'"

.PP
Defines the default configuration key for Server Port\&. 
.SS "#define SITE_DIR_CONF_KEY   'site_root_dir'"

.PP
Defines the default configuration key for website root directory\&. 
.SH "Function Documentation"
.PP 
.SS "char* get_config (const char * key)"

.PP
Returns the value for the corresponding configuration key\&. Key is retrived using the \fCg_key_file_get_value()\fP function\&. The key is expected to valid key defined in configuration file\&. Default keys have macros defined in \fC\fBinclude/config\&.h\fP\fP like \fCHOST_CONF_KEY\fP, \fCPORT_CONF_KEY\fP, etc\&.
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The configuration key\&. 
.RE
.PP
\fBReturns\fP
.RS 4
a newly allocated string or \fCNULL\fP, if the specified key cannot be found\&. 
.RE
.PP

.SS "int get_config_int (const char * key)"

.PP
Returns the int value for the corresponding configuration key\&. Key is retrived using the \fCg_key_file_get_integer()\fP function\&. This function is similar to \fC\fBget_config()\fP\fP except it returns an integer value\&.
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The configuration key\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The value associated with the key as an integer, or \fCINT_MIN\fP, if the key was not found\&. 
.RE
.PP

.SS "char* get_config_str (const char * key)"

.PP
Returns the value for the corresponding configuration key\&. Key is retrived using the \fCg_key_file_get_string()\fP function\&. This function is similar to \fC\fBget_config()\fP\fP except that it handles escape sequences like \fC\\s\fP\&.
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The configuration key\&. 
.RE
.PP
\fBReturns\fP
.RS 4
a newly allocated string or \fCNULL\fP, if the specified key cannot be found\&. 
.RE
.PP

.SS "int load_config ()"

.PP
Loads and parses the configuration file and returns an int value to indicate success or failure\&. Parsing the configuration file is done using the \fCg_key_file_load_from_file()\fP function\&. The config file is loaded from the \fCCONF_FILE\fP macro\&. Cofiguration file is expected to be in INI format\&.
.PP
If the configuration file is loaded successfully, the function returns \fC1\fP and the parsed config is stored in the \fCconfig\fP variable\&. If the configuration file is already loaded (i\&.e\&. \fCconfig\fP is not \fCNULL\fP), the function returns \fC2\fP without performing any action\&. If the configuration file is not loaded successfully, the function returns \fC0\fP\&.
.PP
\fBReturns\fP
.RS 4
On success, returns a non-zero value\&. On failure, returns 0\&. 
.RE
.PP

.SS "void unload_config ()"

.PP
Unloads configuration and frees memory allocated for configuration and any errors\&. 
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for nanows from the source code\&.
