.TH "include/helpers.h" 3 "Mon Jul 26 2021" "Version 2.0" "nanows" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/helpers.h \- Function Prototypes for commonly used helper functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <glib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBltrim\fP (char *s)"
.br
.ti -1c
.RI "char * \fBrtrim\fP (char *s)"
.br
.ti -1c
.RI "char * \fBtrim\fP (char *s)"
.br
.ti -1c
.RI "void \fBfree_gerror\fP (GError **)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Function Prototypes for commonly used helper functions\&. 

This file contains prototypes for commonly used helper functions and eventually any common helper macros, constants, etc\&.
.PP
Implemented in \fC\fBslib/helpers\&.c\fP\fP\&.
.PP
\fBAuthor\fP
.RS 4
Sai Hemanth Bheemreddy (@SaiHemanthBR) 
.RE
.PP
\fBCopyright\fP
.RS 4
MIT License; Copyright (c) 2021 Sai Hemanth Bheemreddy 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void free_gerror (GError ** error)"

.SS "char* ltrim (char * s)"

.SS "char* rtrim (char * s)"

.SS "char* trim (char * s)"

.SH "Author"
.PP 
Generated automatically by Doxygen for nanows from the source code\&.
