.TH "slib/helpers.c" 3 "Mon Jul 26 2021" "Version 2.0" "nanows" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slib/helpers.c \- Collection of commonly used helper functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <ctype\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'helpers\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBltrim\fP (char *s)"
.br
.ti -1c
.RI "char * \fBrtrim\fP (char *s)"
.br
.ti -1c
.RI "char * \fBtrim\fP (char *s)"
.br
.ti -1c
.RI "void \fBfree_gerror\fP (GError **\fBerror\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Collection of commonly used helper functions\&. 

Implements collection of helper functions defined in \fC\fBinclude/helpers\&.h\fP\fP\&.
.PP
\fBAuthor\fP
.RS 4
Sai Hemanth Bheemreddy (@SaiHemanthBR) 
.RE
.PP
\fBCopyright\fP
.RS 4
MIT License; Copyright (c) 2021 Sai Hemanth Bheemreddy 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void free_gerror (GError ** error)"

.SS "char* ltrim (char * s)"

.SS "char* rtrim (char * s)"

.SS "char* trim (char * s)"

.SH "Author"
.PP 
Generated automatically by Doxygen for nanows from the source code\&.
