.TH "request" 3 "Mon Jul 26 2021" "Version 2.0" "nanows" \" -*- nroff -*-
.ad l
.nh
.SH NAME
request
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <request\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBconn_fd\fP"
.br
.ti -1c
.RI "char * \fBhttp_method\fP"
.br
.ti -1c
.RI "char * \fBurl\fP"
.br
.ti -1c
.RI "char * \fBhttp_ver\fP"
.br
.ti -1c
.RI "GHashTable * \fBheader_htab\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int request::conn_fd"

.SS "GHashTable* request::header_htab"

.SS "char* request::http_method"

.SS "char* request::http_ver"

.SS "char* request::url"


.SH "Author"
.PP 
Generated automatically by Doxygen for nanows from the source code\&.
